---
- name: Install dependencies.
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - make
    - build-essential
    - tcl
  become: yes
  
- include_tasks: download-redis.yml
- include_tasks: install-redis.yml
- include_tasks: configure-redis.yml

- include_tasks: sentinel.yml
  when: sentinel.enabled
