---
- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- name: Installing Nginx via apt-get
  apt:
    name: nginx
    state: latest
  become: yes

- name: Adjusting the Firewall
  shell: ufw allow 'Nginx HTTP'
  become: yes

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  become: yes
  notify:
  - restart nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: 
    name: nginx
    state: started
    enabled: yes
  become: yes