---
## This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts except proxmox.
- hosts: all:!proxmox
  gather_facts: false
  roles:
    - common
  tags:
    - common

# Configure Redis key-value storage.
- hosts: redis_master
  roles:
    - role: redis
      sentinel:
        enabled: yes
        master: 
          ip: "{{ hostvars[inventory_hostname]['master'] }}"
          port: "{{ hostvars[groups['redis'][0]]['port'] }}"
        quorum: 2
  tags:
    - redis

- hosts: redis_slave
  roles:
    - role: redis
      sentinel:
        enabled: yes
        master:
          ip: "{{ hostvars[inventory_hostname]['master'] }}"
          port: "{{ hostvars[groups['redis_master'][0]]['port'] }}"
        quorum: 2
  tags:
    - redis

- hosts: rabbitmq
  # tasks:
  #   - name: Test rabbit
  #     debug:
  #       msg: Hello slave!
  #     when: inventory_hostname in groups.rabbitmq_slave
  #   - name: Get master address
  #     debug:
  #       var: hostvars[groups['rabbitmq_master'][0]]['hostname']
  roles:
    - rabbitmq
  tags:
    - rabbitmq
