---
root_folder: /usr/share/nginx/html
keepalive_timeout: 900s
client_header_buffer_size: 1k
client_max_body_size: 1024M
server_names_hash_bucket_size: 128
error_log: "/var/log/nginx/error.log warn"
access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"
upstreams:
  - name: api
    servers: {
      "{{ rest_api_ip }} : {{ rest_api_port }}"
    }
  - name: lyrebird
    servers: {
      "{{ lyrebird_ip }} : {{ lyrebird_port }}"
    }

worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
worker_connections: 1024
server_port: 80