---  
- name: Ensure erlang is installed.
  apt:
    name: erlang
    state: present
  become: yes

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_deb_url }}"
    dest: "/tmp/{{ rabbitmq_deb }}"

- name: Ensure RabbitMQ is installed.
  apt:
    deb: "/tmp/{{ rabbitmq_deb }}"
    state: present
  become: yes

- name: Copy config file.
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  become: yes

- name: Make sure {{ rabbitmq_daemon }} starts at boot
  service:
    name: "{{ rabbitmq_daemon }}"
    enabled: yes
  become: yes  

- name: Start the service.
  service:
    name: "{{ rabbitmq_daemon }}"
    state: started
  become: yes

- name: Enable required RabbitMQ plugins are configured.
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_stomp
    state: enabled
  become: yes
  notify: restart rabbitmq

- import_tasks: cluster-configuration.yml
  when: clustering is defined

