---
rabbitmq_daemon: rabbitmq-server

rabbitmq_version: "3.6.11"

rabbitmq_deb: "rabbitmq-server_{{ rabbitmq_version }}-1_all.deb"
rabbitmq_deb_url: "https://packagecloud.io/rabbitmq/rabbitmq-server/packages/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/{{ rabbitmq_deb }}/download"
#Clustering configurations
clustering:
  errlang_cookie: NVLBSERRLNGRBTCKKIE
  ha:
    name: HA
    mode: all
    queue:
      pattern: ^(?!amq\.).* #^notif[a-zA-Z]*-[a-zA-Z]*[0-9]*

