- name: Prepare hosts file
  lineinfile: 
    dest: /etc/hosts
    regexp: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostvars[inventory_hostname]['hostname'] }}"
    line: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostvars[inventory_hostname]['hostname'] }}"
    state: present
  become: yes

- name: Set hostname
  hostname:
    name: "{{ hostvars[inventory_hostname]['hostname'] }}"
  become: yes